version: '3'
services:
  kb:
    image: "library/kibana:7.3.1"
    container_name: "kb"
    logging:
      driver: "json-file"
      options:
        labels: "servicename"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        max-size: "100m"
        max-file: "10"
    labels:
      servicename: "kb"
    ports:
      - "5601:5601"
    environment:
      TZ: "Asia/Shanghai"
      ELASTICSEARCH_HOSTS: "http://es:9200"
    depends_on:
      - "es"
    networks: 
      - dev-network
    restart: always
  es:
    image: "elasticsearch:7.3.1"
    container_name: "es"
    logging:
      driver: "json-file"
      options:
        labels: "servicename"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        max-size: "100m"
        max-file: "10"
    labels:
      servicename: "es"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
      TZ: "Asia/Shanghai"
    networks: 
      - dev-network
    restart: always
  fb:
    image: "docker.elastic.co/beats/filebeat:7.3.1"
    container_name: "fb"
    environment:
      output.logstash.enabled: 0
      TZ: "Asia/Shanghai"
    volumes:
      - /home/yf/projects/fpm-iot/iot-app.yunplus.io/app.log:/home/app.log:ro
      - /home/yf/projects/fpm-iot/iot-app.yunplus.io/error.log:/home/error.log:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/fields.yml:/fields.yml
    depends_on:
      - "es"
      - "kb"
    networks: 
      - dev-network
  fluentd:
    image: quay.io/fluentd_elasticsearch/fluentd:v3.0.2
    logging:
      driver: "json-file"
      options:
        labels: "servicename"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
        max-size: "100m"
        max-file: "10"
    labels:
      servicename: "fluentd"
    ports:
      - 9880:9880
    volumes:
      - ./config.conf:/etc/fluent/config.d/my.conf
      - /home/yf/projects/fpm-iot/deploy-fpm-iot-server/log/:/var/log/server/
    networks: 
      - dev-network
    depends_on:
      - "es"
      - "kb"
networks:
  dev-network: 
      