version: '3'
services:
  kb:
    image: "library/kibana:7.3.1"
    container_name: "kb"
    ports:
      - "5601:5601"
    environment:
      TZ: "Asia/Shanghai"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - "es"
    networks: 
      - dev-network
    restart: always
  es:
    image: "elasticsearch:7.3.1"
    container_name: "es"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      TZ: "Asia/Shanghai"
    networks: 
      - dev-network
    restart: always
  gf:
    image: "grafana/grafana"
    container_name: "gf"
    ports:
      - "3000:3000"
    environment:
      TZ: "Asia/Shanghai"
    networks: 
      - dev-network
    restart: always
  fb:
    image: "docker.elastic.co/beats/filebeat:7.3.1"
    container_name: "fb"
    environment:
      output.logstash.enabled: 0
      TZ: "Asia/Shanghai"
    volumes:
      - ./filebeat/test.log:/home/rocket.log:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/fields.yml:/fields.yml
    depends_on:
      - "es"
      - "kb"
    networks: 
      - dev-network
    restart: always
networks:
  dev-network: 
