version: '3'
services:
  es:
    image: "elasticsearch:7.3.1"
    container_name: "es"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks: 
      - dev-network
    restart: always
  fb:
    image: "prima/filebeat"
    container_name: "fb"
    volumes:
      - ./filebeat/test.log:/var/log/command.log:ro
      - ./filebeat/filebeat.yml:/filebeat.yml
    networks: 
      - dev-network
    restart: always
networks:
  dev-network: 
