version: '3'
services:
  es:
    image: "elasticsearch:7.3.1"
    container_name: "es"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
    networks: 
      - dev-network
    restart: always
  fb:
    image: "docker.elastic.co/beats/filebeat:7.3.1"
    # image: "prima/filebeat"
    # build: 'filebeat/.'
    container_name: "fb"
    environment:
      output.logstash.enabled: 0
    volumes:
      - ./filebeat/test.log:/var/log/rocket.log:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/fields.yml:/fields.yml
    depends_on:
      - "es"
    networks: 
      - dev-network
    restart: always
networks:
  dev-network: 
