version: '3'
services:
  influxdb:
    image: "influxdb:1.7-alpine"
    container_name: "influxdb"
    ports:
      - "19783:8083"
      - "19786:8086"
    volumes:
      - ./influxdb/data/:/var/lib/influxdb
      - ./influxdb/NOAA_data.txt:/NOAA_data.txt
    environment:
      TZ: "Asia/Shanghai"
      INFLUX_USERNAME: "admin"
      INFLUX_PASSWORD: "password"
    networks: 
      - dev-network
    restart: always
  redis:
    image: 'redis:alpine3.11'
    restart: always
    hostname: redis
    container_name: redis-server
    ports:
      - 6379:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis_config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/redis_data/:/data/
    networks: 
      - dev-network
    restart: always
networks:
  dev-network: 