version: '3.1'

services:
  my-rabbit:
    image: rabbitmq:3
    restart: always
    container_name: some-rabbit
    hostname: my-rabbit
    ports:
      - 5672:5672
    environment:
      RABBITMQ_ERLANG_COOKIE: secret
      RABBITMQ_NODENAME: rabbit@some-rabbit

  my-rabbit-mgmt:
    image: rabbitmq:3-management
    restart: always
    hostname: my-rabbit-mgmt
    ports:
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

 